### ISSUE TITLE
Usage with Apollo Server 

### ISSUE THREAD

**Issue by riginoommen** [Julien-R44/bentocache#3]
Can bentocache used for caching with apollographql if yes can you please provide an example

**Comment by Julien-R44** [comment]
I assume you're talking about Apollo Server. According to this page: https://www.apollographql.com/docs/apollo-server/performance/cache-backends/

It's perfectly possible, and even seems quite simple. In fact, all you'd have to do is make an adapter for bentocache. And when you look at the code for the `Keyv` adapter, it's quite simple: https://github.com/apollographql/apollo-utils/blob/main/packages/keyvAdapter/src/index.ts

Just define get and set method, basically.

Since I don't use Apollo Server, I don't intend to develop this, not for the moment at least. Feel free to try and don't hesitate to ask if you have any problem !

**Comment by Julien-R44** [comment]
Closing the issue, feel free to re-open if help needed.
