### ISSUE TITLE
Cache eviction on File System dirver

### ISSUE THREAD

**Issue by bkodirov** [Julien-R44/bentocache#7]
Great project!

I am going to leverage GCP Cloud Run container disk as a cache to decrease DB requests. 

In theory, you will run out of disk space if you keep writing data back to disk without evicting the oldest one. 
It would be a good idea to introduce some kind of data eviction policy like LRU?

Many thanks.

**Comment by Julien-R44** [comment]
Hello! 

So, to explain quickly: some drivers have a TTL driver. Typically Redis or DynamoDB. In this case: no problem, when the TTL expires, the entry is completely deleted.

Other drivers don't: filesystem or databases. In this case, it's more complicated. 

I've tried a simple implementation with database drivers: just run a `setInterval` that will delete expired entries every X seconds/minutes/hours. See https://github.com/Julien-R44/bentocache/blob/main/packages/bentocache/src/drivers/sql.ts#L66

The implementation is rather naive but it seems to works fine for now. I was planning to use a [worker](https://nodejs.org/api/worker_threads.html) Node for this, but it's still on standby

So, for the filesystem, I suppose we can start by having a fairly similar implementation. Just a `setInterval`. Having said that, the implementation is likely to be a little more costly than with the database. We have to scan and open all the files to check the TTLs. We will probably have to do some benchmarking to make sure it's not too performance-intensive. Or use a worker right now instead of a simple setInterval

Any thoughts ?

**Comment by Julien-R44** [comment]
Was implemented with #13 and will be available in next release

**Comment by Julien-R44** [comment]
Published with bentocache@1.0.0-beta.8
